### PR TITLE
Add new/update tons of tests

### PR DESCRIPTION
**Pull request by Ghabry**
Few, lots of work... Havn't retested all stuff yet (adding white color below). Is "just" adding/editing events.

Money, Item, Hero, Experience, Level, Parameters, Equip, HP/MP Recover, Status, Damage, Change hero name, Change Vehicle, Change System, Branch. Completely NEW: Teleport/Escape, Change Event Position, Swap Event, Get Terrain ID, Get Event ID, Key Input, Loop/Label, Delete event, Panorama, Tile substitution, Call Event.

Adding a new common event (update LDB). Moving back to event test map is now more clever and remembers position.

### CODE REVIEW

**Comment by Ghabry** [comment]
Don't forget to publish it on the website as new game in default folder ^^

**Comment by carstene1ns** [comment]
Will do. And I think it is safe to remove the additional 'testgame-2000' folder to avoid fragmentation and inconsistency.
If needed a symlink could be used.

**Comment by Ghabry** [comment]
yeah this folder is unnecessary

**Comment by carstene1ns** [comment]
Updated.

**Pull request merged**
